version: '3.7'

services:
  postgres:
    container_name: '${APP_NAME}_postgres'
    image: postgres:alpine
    volumes:
      - /postgres-data:/var/lib/postgresql/data
    restart: always
    ports:
      - '5432:5432'
    networks:
      - default
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    restart: on-failure
networks:
  default:
    driver: bridge
    